version: "2"

services:
  ### ioBroker ########################################
  iobroker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./transfer:/opt/transfer
    ports:
      - 9081:8081
      - 9082:8082
      - 9083:8083
      - 9084:8084