version: "2"

services:
  ### ioBroker ########################################
  iobroker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./transfer:/opt/transfer
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 8084:8084